version: 0.0.9.{build}
os: Visual Studio 2015
configuration: Release
clone_folder: C:\projects\fuwateawin
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- choco install -y InnoSetup
- set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
- git submodule -q update --init
- del ModularFramework\ModularFramework.sln
before_build:
- nuget restore
build:
  verbosity: minimal
after_build:
- iscc /DVersionNumber=%APPVEYOR_BUILD_VERSION% Installer\installer.iss
- 7z a ftwplayer_portable.zip bin\Release\*.dll
- 7z a ftwplayer_portable.zip bin\Release\*.exe
- 7z a ftwplayer_portable.zip bin\Release\logconfig.xml
- 7z a ftwplayer_portable.zip bin\Release\logconfig-debug.xml
- 7z a ftwplayer_portable.zip bin\Release\he
artifacts:
- path: ftwplayer_portable.zip
  name: Portable
- path: Installer\Output\ftwplayer_setup.exe
  name: Installer
deploy:
- provider: Local
