//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTWPlayer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FTWPlayer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to {0}&apos;s playlist.
        /// </summary>
        internal static string AddToPlaylistFormatString {
            get {
                return ResourceManager.GetString("AddToPlaylistFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Settings.
        /// </summary>
        internal static string AllSettings {
            get {
                return ResourceManager.GetString("AllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported playlist types.
        /// </summary>
        internal static string AllSupportedPlaylists {
            get {
                return ResourceManager.GetString("AllSupportedPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has crashed!.
        /// </summary>
        internal static string AppCrash {
            get {
                return ResourceManager.GetString("AppCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A compact, modular and open-source music player.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Compact Mode.
        /// </summary>
        internal static string CompactToolTip {
            get {
                return ResourceManager.GetString("CompactToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQUALIZER.
        /// </summary>
        internal static string EqualizerTabHeader {
            get {
                return ResourceManager.GetString("EqualizerTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Mode.
        /// </summary>
        internal static string ExclusiveMode {
            get {
                return ResourceManager.GetString("ExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitToolTip {
            get {
                return ResourceManager.GetString("ExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Expanded Mode.
        /// </summary>
        internal static string ExpandToolTip {
            get {
                return ResourceManager.GetString("ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string FileTypeFormatString {
            get {
                return ResourceManager.GetString("FileTypeFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string HelpTabHeader {
            get {
                return ResourceManager.GetString("HelpTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window.
        /// </summary>
        internal static string HideToolTip {
            get {
                return ResourceManager.GetString("HideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIBRARY.
        /// </summary>
        internal static string LibraryTabHeader {
            get {
                return ResourceManager.GetString("LibraryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently loaded skin:.
        /// </summary>
        internal static string LoadedSkin {
            get {
                return ResourceManager.GetString("LoadedSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextToolTip {
            get {
                return ResourceManager.GetString("NextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output API:.
        /// </summary>
        internal static string OutputAPI {
            get {
                return ResourceManager.GetString("OutputAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device:.
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseToolTip {
            get {
                return ResourceManager.GetString("PauseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string PlaybackSettings {
            get {
                return ResourceManager.GetString("PlaybackSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        internal static string PlayerTabHeader {
            get {
                return ResourceManager.GetString("PlayerTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string PlayToolTip {
            get {
                return ResourceManager.GetString("PlayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with {0}.
        /// </summary>
        internal static string PlayWithFormatString {
            get {
                return ResourceManager.GetString("PlayWithFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousToolTip {
            get {
                return ResourceManager.GetString("PreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat (Entire list).
        /// </summary>
        internal static string RepeatAllToolTip {
            get {
                return ResourceManager.GetString("RepeatAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat (Off).
        /// </summary>
        internal static string RepeatOffToolTip {
            get {
                return ResourceManager.GetString("RepeatOffToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat (Current song).
        /// </summary>
        internal static string RepeatSingleToolTip {
            get {
                return ResourceManager.GetString("RepeatSingleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string ResumeToolTip {
            get {
                return ResourceManager.GetString("ResumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SettingsTabHeader {
            get {
                return ResourceManager.GetString("SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string ShowToolTip {
            get {
                return ResourceManager.GetString("ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle (Off).
        /// </summary>
        internal static string ShuffleOffToolTip {
            get {
                return ResourceManager.GetString("ShuffleOffToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle (On).
        /// </summary>
        internal static string ShuffleOnToolTip {
            get {
                return ResourceManager.GetString("ShuffleOnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        internal static string Skins {
            get {
                return ResourceManager.GetString("Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopToolTip {
            get {
                return ResourceManager.GetString("StopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAGS.
        /// </summary>
        internal static string TagsTabHeader {
            get {
                return ResourceManager.GetString("TagsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occured! See ftw.log for more information.
        ///Please report this to the author with a copy of ftw.log..
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string VolumeToolTip {
            get {
                return ResourceManager.GetString("VolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuwaTeaWin Testing Version.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
