[CustomMessages]
MainFiles=
GUILanguages=
Hebrew=
Icons=
CreateDesktopIcon=
Tasks=
UpdateFileAssociations=
ResetConfig=
UninstallIcon=
FileExtGeneric=
PlayWith=
AddToPlaylist=
AppDescription=
UpdatingFileAssociations=
ConfigureFileAssociations=
